name: springbootapp_CI

on:
  push:
    branches:
      - main 
  pull_request: 
    branches:
      - main
  #workflow_dispatch:
    #inputs:
      #environment:
        #description: 'Environment to deploy to'
        #required: true
        #default: 'development'
        #type: choice
        #options:
          #- development
          #- staging
          #- production
#permissions:
  #contents: read # Default for pushes is write, so this explicitly lowers it
  #pull-requests: write # Explicitly grant write access for PRs if needed
  #issues: write # Allow workflow to create/update issues
  #packages: write # Allow publishing packages
env:
  DOCKER_USERNAME: sureshc2024
  DOCKER_REPO: springboot
jobs:
  build-and-push:
    runs-on: ubuntu
    strategy:
      matrix:
        java: [ '21', '17' ] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        #with:
          #repository: your-org/another-private-repo # The other repository
          #token: ${{ secrets.MY_PAT }} # Use your PAT stored as a secret
          #path: another-repo-directory # Where to clone it

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Run Tests
        run: mvn -B clean package -DskipTests --file pom.xml
        
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar-${{ matrix.java }}
          path: target/*.jar
          
      #- name: Log in to Docker Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: docker.io 
      #     username: ${{ env.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Docker image (Unique Tag per Matrix Variant)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{env.DOCKER_USERNAME}}/${{env.DOCKER_REPO}}:${{ matrix.java }}
