on:
  push:
    branches:
      - main 
  pull_request: 
    branches:
      - main

env:
  DOCKER_IMAGE_BASE: ${{ secrets.DOCKER_USERNAME }}/java-microservice 
jobs:
  build-and-push:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '17', '21' ] 
        os: [ ubuntu-latest, windows-latest ] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }} on ${{ matrix.os }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Run Tests
        run: mvn -B clean package -DskipTests --file pom.xml
        
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar-${{ matrix.java }}
          path: target/*.jar

      #- name: Build and Push Docker image (Unique Tag per Matrix Variant)
       # uses: docker/build-push-action@v5
        #with:
         # context: .
          #push: true
          #tags: ${{ env.DOCKER_IMAGE_BASE }}:${{ github.sha }}-${{ matrix.os }}-${{ matrix.java }}
